### PR TITLE
Ensure that Validation.type returns correct value

### LINKED ISSUE #59: Validation type is incorrect
I'm using the Product template on a new space. The Brand Website field is validated by regex. contentful-management says the type is 'Present'

```ruby
(byebug) field.validations.first.type
:present
```

It seems to be the test on this line:
https://github.com/contentful/contentful-management.rb/blob/master/lib/contentful/management/validation.rb#L28

checking for nil, but present and linkField are booleans and are set to false, not nil.

### PR DESCRIPTION
**Pull request by neonichu**
Fixes #59

### CODE REVIEW

File: lib/contentful/management/validation.rb [hunk 1]
```diff
@@ -24,8 +24,9 @@ def properties_to_hash
 
       # Returns type of validation
       def type
-        properties.keys.each do |type|
-          return type if !self.send(Support.snakify(type)).nil?
+        properties.keys.reject { |key| key == :validations }.each do |type|
+          value = self.send(Support.snakify(type))
+          return type if !value.nil? && value
```
Comment (pxlpnk) [inline lib/contentful/management/validation.rb]: `!value.nil? && value`
this seems a bit redundant. or can value be `false` here?
