### PR TITLE
Fix #save method

### LINKED ISSUE #189: Calling save on Webhook produces BadRequest where as calling update succeeds
Given a webhook (probably true for other resources, not tested)
```
client = Contentful::Management::Client.new(ENV.fetch('ACCESS_TOKEN'))
webhook = client.webhook(ENV.fetch('SPACE_ID')).find('WEBHOOK_ID')
```

Using the assign and save method causes BadRequest:
```
webhook.url = 'https://www.example.com/the/path/to/stuff'
webhook.save                                                                                                                                                                                                            
=> #<Contentful::Management::BadRequest: HTTP status code: 400 Bad Request Message: 
The request was malformed or missing a required parameter.
Message: The request was malformed or missing a required parameter.>
```

Where as using `update` works just fine:
```
webhook.update(url: 'https://www.example.com/the/path/to/stuff')
=> #<Contentful::Management::Webhook: @properties={:url=>"https://example.com/the/path/to/stuff", :name=>"ContentType publishing", :topics=>["ContentType.publish"], :headers=>[], :httpBasicUsername=>nil, :filters=>nil, :transformation=>nil} @sys={:type=>"WebhookDefinition", :id=>"WEBHOOK_ID", :version=>9, :space=>...
```

### PR DESCRIPTION
**Pull request by dlitvakb**
Fixes #189 

The issue only reports that `Webhook`s are not properly saving, but the same is true for several other entities that had that method enabled on version `2.5.0`. This PR addresses those resources.

### CODE REVIEW

File: spec/lib/contentful/management/locale_spec.rb [hunk 1]
```diff
@@ -161,14 +161,29 @@ module Management
...
+        let(:space_id) { 'facgnwwgj5fe' }
         it 'should be able to create a locale with a fallback code' do
           vcr('locale/fallback_code') do
             locale = subject.create(name: 'Foo (BarBaz)', code: 'foo-BB', fallback_code: 'en-US')
 
             expect(subject.find(locale.id).code).to eq 'foo-BB'
           end
         end
+
+        it 'can save a locale - #189' do
```
Comment (makinwab) [inline spec/lib/contentful/management/locale_spec.rb]: Since the newly added tests have similar implementations, maybe you could use a [shared_example](https://relishapp.com/rspec/rspec-core/v/3-8/docs/example-groups/shared-examples) and pass arguments for things that vary for each test case.

OR

Ignore the above and leave this as is, if it aids readability/clarity when compared to using shared examples. :)

Comment (dlitvakb) [reply spec/lib/contentful/management/locale_spec.rb]: Thanks @makinwab,

I'll keep it as is for the sake of increasing readability, but will start looking into opportunities for creating shared examples in the future.

Cheers
